import Foundation

public enum EdgeFlag {
    public static let crossing: UInt8 = 1 << 0
    /// A way drawn down one side of a street (`footway=sidewalk`): two per street,
    /// which is what lets the sun layer colour the sides differently.
    public static let sidewalk: UInt8 = 1 << 1
    public static let steps: UInt8 = 1 << 2
    /// A street centreline tagged `sidewalk=both|left|right`. Sidewalks exist there,
    /// but the geometry is still one line down the middle of the road, so this edge
    /// cannot distinguish the two sides. Never conflate it with `.sidewalk`.
    public static let streetSidewalkTag: UInt8 = 1 << 3
    /// Generated by the pipeline's sidewalk synthesis rather than drawn in OSM.
    public static let synthetic: UInt8 = 1 << 4
    /// A road centreline that survived synthesis: walked down the middle because at
    /// least one side has no sidewalk (or the street is a service road/alley).
    public static let street: UInt8 = 1 << 5
    /// OSM `access=private`: a gated tract or HOA street. Walkable for residents; not a
    /// through-route for anyone else. Kept in the bundle format; the sun field ignores it.
    public static let privateAccess: UInt8 = 1 << 6
}

/// Immutable pedestrian street graph in CSR (compressed sparse row) form.
/// Sidewalks and crossings are kept as their own edges — never collapsed onto a
/// street centreline — because the sun layer has to be able to tell one side of
/// a street from the other.
public final class PedestrianGraph {
    public let nodeLat: [Double]
    public let nodeLon: [Double]

    public let edgeA: [Int32]
    public let edgeB: [Int32]
    public let edgeLen: [Double]
    public let edgeFlags: [UInt8]
    public let edgeInterest: [UInt8]

    /// CSR adjacency: neighbours of node i are adjNode[adjStart[i]..<adjStart[i+1]].
    public let adjStart: [Int32]
    public let adjNode: [Int32]
    public let adjEdge: [Int32]

    public let bbox: BBox
    private let grid: SpatialGrid

    /// Connected-component id per node. OSM walking extracts are full of tiny
    /// disconnected islands (a pier footway, a plaza clipped by the extract);
    /// snapping a destination onto one makes it look unreachable, so every snap
    /// is component-aware.
    public private(set) var component: [Int32] = []
    public private(set) var componentSizes: [Int] = []
    public private(set) var largestComponent: Int32 = 0

    public var nodeCount: Int { nodeLat.count }
    public var edgeCount: Int { edgeA.count }

    @inline(__always) public func isCrossing(_ edge: Int) -> Bool {
        edgeFlags[edge] & EdgeFlag.crossing != 0
    }
    /// True only for separate per-side sidewalk geometry.
    @inline(__always) public func isSidewalk(_ edge: Int) -> Bool {
        edgeFlags[edge] & EdgeFlag.sidewalk != 0
    }

    @inline(__always) public func isStreetCentreline(_ edge: Int) -> Bool {
        edgeFlags[edge] & EdgeFlag.street != 0
    }
    @inline(__always) public func isPrivate(_ edge: Int) -> Bool {
        edgeFlags[edge] & EdgeFlag.privateAccess != 0
    }
    @inline(__always) public func isSynthetic(_ edge: Int) -> Bool {
        edgeFlags[edge] & EdgeFlag.synthetic != 0
    }

    /// True for a street centreline that merely records sidewalks exist.
    @inline(__always) public func isStreetWithSidewalkTag(_ edge: Int) -> Bool {
        edgeFlags[edge] & EdgeFlag.streetSidewalkTag != 0
    }

    /// Designated initialiser: CSR adjacency already built (the bundle path).
    public init(nodeLat: [Double], nodeLon: [Double],
                edgeA: [Int32], edgeB: [Int32], edgeLen: [Double],
                edgeFlags: [UInt8], edgeInterest: [UInt8],
                adjStart: [Int32], adjNode: [Int32], adjEdge: [Int32],
                bbox: BBox) {
        self.nodeLat = nodeLat; self.nodeLon = nodeLon
        self.edgeA = edgeA; self.edgeB = edgeB; self.edgeLen = edgeLen
        self.edgeFlags = edgeFlags; self.edgeInterest = edgeInterest
        self.adjStart = adjStart; self.adjNode = adjNode; self.adjEdge = adjEdge
        self.bbox = bbox
        self.grid = SpatialGrid(lat: nodeLat, lon: nodeLon, bbox: bbox)
        computeComponents()
    }

    /// Convenience initialiser that builds the CSR adjacency itself. Used by tests
    /// and by any in-memory graph construction.
    public convenience init(nodeLat: [Double], nodeLon: [Double],
                            edgeA: [Int32], edgeB: [Int32], edgeLen: [Double],
                            edgeFlags: [UInt8]? = nil, edgeInterest: [UInt8]? = nil,
                            bbox: BBox) {
        let n = nodeLat.count
        var degree = [Int32](repeating: 0, count: n + 1)
        for i in 0..<edgeA.count {
            degree[Int(edgeA[i])] += 1
            degree[Int(edgeB[i])] += 1
        }
        var start = [Int32](repeating: 0, count: n + 1)
        var running: Int32 = 0
        for i in 0...n {
            start[i] = running
            if i < n { running += degree[i] }
        }
        var cursor = start
        var aNode = [Int32](repeating: 0, count: edgeA.count * 2)
        var aEdge = [Int32](repeating: 0, count: edgeA.count * 2)
        for i in 0..<edgeA.count {
            let a = Int(edgeA[i]), b = Int(edgeB[i])
            aNode[Int(cursor[a])] = edgeB[i]; aEdge[Int(cursor[a])] = Int32(i); cursor[a] += 1
            aNode[Int(cursor[b])] = edgeA[i]; aEdge[Int(cursor[b])] = Int32(i); cursor[b] += 1
        }
        self.init(nodeLat: nodeLat, nodeLon: nodeLon,
                  edgeA: edgeA, edgeB: edgeB, edgeLen: edgeLen,
                  edgeFlags: edgeFlags ?? [UInt8](repeating: 0, count: edgeA.count),
                  edgeInterest: edgeInterest ?? [UInt8](repeating: 0, count: edgeA.count),
                  adjStart: start, adjNode: aNode, adjEdge: aEdge, bbox: bbox)
    }

    private func computeComponents() {
        var comp = [Int32](repeating: -1, count: nodeCount)
        var sizes: [Int] = []
        var stack: [Int32] = []
        for seed in 0..<nodeCount where comp[seed] == -1 {
            let id = Int32(sizes.count)
            comp[seed] = id
            stack.removeAll(keepingCapacity: true)
            stack.append(Int32(seed))
            var size = 0
            while let u = stack.popLast() {
                size += 1
                for k in Int(adjStart[Int(u)])..<Int(adjStart[Int(u) + 1]) {
                    let v = adjNode[k]
                    if comp[Int(v)] == -1 { comp[Int(v)] = id; stack.append(v) }
                }
            }
            sizes.append(size)
        }
        component = comp
        componentSizes = sizes
        largestComponent = Int32(sizes.enumerated().max { $0.element < $1.element }?.offset ?? 0)
    }

    /// Components big enough to be a real street network rather than a stray plaza.
    /// In a stitched metro the largest component is not "the city": the loaded tiles
    /// can hold Manhattan and a piece of Staten Island, each a network in its own right.
    public static let minimumNetworkNodes = 300

    @inline(__always) public func isNetworkComponent(_ id: Int32) -> Bool {
        componentSizes[Int(id)] >= min(PedestrianGraph.minimumNetworkNodes, componentSizes[Int(largestComponent)])
    }

    public func coordinate(_ n: Int32) -> (lat: Double, lon: Double) {
        (nodeLat[Int(n)], nodeLon[Int(n)])
    }

    /// Edge indices whose midpoint lies within `radius` metres of a point.
    public func edges(near lat: Double, lon: Double, radius: Double) -> [Int32] {
        let nodes = grid.nodes(near: lat, lon: lon, radius: radius,
                               nodeLat: nodeLat, nodeLon: nodeLon)
        var seen = Set<Int32>()
        var out: [Int32] = []
        for n in nodes {
            for k in Int(adjStart[Int(n)])..<Int(adjStart[Int(n) + 1]) {
                let e = adjEdge[k]
                if seen.insert(e).inserted { out.append(e) }
            }
        }
        return out
    }

    /// Edges with at least one end inside a box — what is on screen.
    public func edges(in box: BBox) -> [Int32] {
        let cLat = box.centerLat, cLon = box.centerLon
        let radius = haversineMeters(box.minLat, box.minLon, box.maxLat, box.maxLon) / 2 + 1
        let nodes = grid.nodes(near: cLat, lon: cLon, radius: radius, nodeLat: nodeLat, nodeLon: nodeLon)
        var seen = Set<Int32>()
        var out: [Int32] = []
        for n in nodes where box.contains(lat: nodeLat[Int(n)], lon: nodeLon[Int(n)]) {
            for k in Int(adjStart[Int(n)])..<Int(adjStart[Int(n) + 1]) {
                let e = adjEdge[k]
                if seen.insert(e).inserted { out.append(e) }
            }
        }
        return out
    }
}
