"""Binary format for the city bundle consumed by SunMapEngine.

All integers little-endian. Coordinates are fixed-point degrees * 1e7 (~1.1 cm).
Every section starts on an 8-byte boundary.

  header (64 bytes)
    magic       4s   b"LWB1"
    version     u32  = 1
    nodeCount   u32
    edgeCount   u32
    bldCount    u32
    bldVertCount u32
    minLat/minLon/maxLat/maxLon  f64 x 4
    reserved    u32 x 2            (version 3: i32 tile row, i32 tile col)

  sections, in order
    nodeLatE7    i32 * nodeCount
    nodeLonE7    i32 * nodeCount
    adjStart     u32 * (nodeCount + 1)
    adjNode      u32 * (2 * edgeCount)
    adjEdge      u32 * (2 * edgeCount)
    edgeA        u32 * edgeCount
    edgeB        u32 * edgeCount
    edgeLen      f32 * edgeCount
    edgeFlags    u8  * edgeCount     (bit0 crossing, bit1 sidewalk geometry,
                                      bit2 steps, bit3 centreline tagged with sidewalk=*,
                                      bit4 synthesised by the pipeline,
                                      bit5 surviving road centreline,
                                      bit6 access=private)
    edgeInterest u8  * edgeCount
    bldStart     u32 * (bldCount + 1)
    bldLatE7     i32 * bldVertCount
    bldLonE7     i32 * bldVertCount
    bldHeight    f32 * bldCount
    -- version 2 --
    bldGround    f32 * bldCount        ground elevation under each footprint, m
    terrainHdr   u32 rows, u32 cols, f64 originLat, f64 originLon, f64 stepLat, f64 stepLon
    terrain      i16 * (rows * cols)   ground elevation, m, row-major from originLat/originLon
    -- version 3 (one tile of a metro) --
    nodeGlobalId u32 * nodeCount       metro-wide node id; the app stitches tiles on it.
                                       Terrain in a tile sits on the metro's shared lattice
                                       (origin = integer multiple of step), so tiles mosaic
                                       exactly.
"""
import struct
import numpy as np

MAGIC = b"LWB1"
VERSION = 2
HEADER_SIZE = 64

FLAG_CROSSING = 1 << 0
# A way actually drawn down one side of a street (footway=sidewalk). This is the
# flag that means "there is a separate edge per side", which the sun layer needs.
FLAG_SIDEWALK = 1 << 1
FLAG_STEPS = 1 << 2
# A street centreline carrying a sidewalk=both|left|right tag. It records that
# sidewalks exist but is still a single line down the middle of the road, so it
# cannot tell one side from the other. Deliberately NOT the same flag as above.
FLAG_STREET_SIDEWALK_TAG = 1 << 3
# Edge generated by sidewalks.py rather than drawn in OSM.
FLAG_SYNTHETIC = 1 << 4
# A road centreline (highway=residential/tertiary/...) that survived synthesis: walked
# along the middle because no sidewalk exists on one or both sides.
FLAG_STREET = 1 << 5
# OSM access=private: a gated tract, HOA street, or private road. Walkable for the
# people who live there; not a through-route for anyone else.
FLAG_PRIVATE = 1 << 6


def _pad(f):
    extra = f.tell() % 8
    if extra:
        f.write(b"\0" * (8 - extra))


def write_bundle(path, *, node_lat, node_lon, adj_start, adj_node, adj_edge,
                 edge_a, edge_b, edge_len, edge_flags, edge_interest,
                 bld_start, bld_lat, bld_lon, bld_height, bbox,
                 bld_ground=None, terrain=None, global_ids=None, tile=(0, 0)):
    """Writes version 2, or version 3 when `global_ids` is given: a tile of a metro,
    whose nodes carry metro-wide ids so the app can stitch neighbouring tiles, and
    whose header's reserved words hold the tile's (row, col) on the metro lattice."""
    node_count = len(node_lat)
    edge_count = len(edge_a)
    bld_count = len(bld_height)
    bld_vert = len(bld_lat)

    def e7(arr):
        return np.rint(np.asarray(arr, dtype=np.float64) * 1e7).astype("<i4")

    with open(path, "wb") as f:
        for name, n in (("nodes", node_count), ("edges", edge_count), ("buildings", bld_count),
                        ("vertices", bld_vert)):
            assert n < 2 ** 31, f"{name} count {n} exceeds the reader's Int32 indices"
        version = 3 if global_ids is not None else VERSION
        f.write(struct.pack("<4sIIIII", MAGIC, version, node_count, edge_count,
                            bld_count, bld_vert))
        f.write(struct.pack("<4d", *bbox))
        f.write(struct.pack("<ii", int(tile[0]), int(tile[1])))
        assert f.tell() == HEADER_SIZE, f.tell()

        for arr, dtype in [
            (e7(node_lat), None), (e7(node_lon), None),
            (np.asarray(adj_start, dtype="<u4"), None),
            (np.asarray(adj_node, dtype="<u4"), None),
            (np.asarray(adj_edge, dtype="<u4"), None),
            (np.asarray(edge_a, dtype="<u4"), None),
            (np.asarray(edge_b, dtype="<u4"), None),
            (np.asarray(edge_len, dtype="<f4"), None),
            (np.asarray(edge_flags, dtype="<u1"), None),
            (np.asarray(edge_interest, dtype="<u1"), None),
            (np.asarray(bld_start, dtype="<u4"), None),
            (e7(bld_lat), None), (e7(bld_lon), None),
            (np.asarray(bld_height, dtype="<f4"), None),
        ]:
            _pad(f)
            f.write(arr.tobytes())
        # version 2
        _pad(f)
        ground = np.zeros(bld_count, dtype="<f4") if bld_ground is None else np.asarray(bld_ground, dtype="<f4")
        f.write(ground.tobytes())
        _pad(f)
        if terrain is None:
            f.write(struct.pack("<IIdddd", 0, 0, 0.0, 0.0, 0.0, 0.0))
        else:
            f.write(struct.pack("<IIdddd", terrain["rows"], terrain["cols"],
                                terrain["origin_lat"], terrain["origin_lon"],
                                terrain["step_lat"], terrain["step_lon"]))
            _pad(f)
            f.write(np.asarray(terrain["elevation"], dtype="<i2").tobytes())
        _pad(f)
        if global_ids is not None:
            # version 3
            f.write(np.asarray(global_ids, dtype="<u4").tobytes())
            _pad(f)
    return {
        "nodes": node_count, "edges": edge_count,
        "buildings": bld_count, "building_vertices": bld_vert,
    }
